version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    # volumes:
    #   - ./backend:/usr/src/app
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # volumes:
    #   - ./frontend:/usr/src/app
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=http://backend:5003
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
